---
- name: Check that password for keystore is defined
  assert:
    that: corda_password_keystore is defined
    msg: "Having password to keystore in config file is not ideal, but for now please set 'corda_password_keystore' to a value"

# Get the variables specific for Linux distributions
- include_vars: '{{ item }}'
  with_first_found:
    - default.yml
#    - "{{ ansible_distribution | lower }}.yml"

- name: Get version of Java
  command: java -version
  register: _corda_java_version_check
  changed_when: false
  failed_when: false

- name: Check Java has been installed
  assert:
    that: _corda_java_version_check.stderr is defined
    msg: 'Please make sure java has been installed before starting this Ansible role'

- name: Check the Java version
  assert:
    that:
      - '"build 1.8.0" in (_corda_java_version_check.stderr | default(""))'
    msg: 'Please make sure correct Java binary has been installed, the java -version returned "{{ _corda_java_version_check.stderr }}"'

# For Ubuntu
- include: ubuntu.yml
  when: (ansible_distribution | lower ) in ['ubuntu']

# For Centos
- include: centos.yml
  when: (ansible_distribution | lower ) in ['centos', 'redhat', 'amazon']

- name: Create group
  become: yes
  group:
    name: "{{ corda_user }}"
    state: present

- name: Create user
  become: yes
  user:
    name: "{{ corda_user }}"
    groups: "{{ corda_user }}"
    state: present
    createhome: no
    shell: /bin/false

- name: Prepare Corda directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ corda_user }}"
    group: "{{ corda_user }}"
    mode: 0755
  loop:
      - "{{ corda_dir_location }}"
      - "{{ corda_dir_location }}/certificates"

# Service manager specific configuration
- include_tasks: '{{ service_mgr }}'
  loop_control:
    loop_var: service_mgr
  with_first_found:
    - '{{ ansible_service_mgr }}.yml'
    - default.yml

- name: Install config file (version 3+)
  become: yes
  template:
    src: node.conf.j2
    dest: "{{ corda_conf_location }}/node.conf"
    owner: "{{ corda_user }}"
    group: "{{ corda_user }}"
    mode: 0755
  when: corda_version is version_compare('3','>=')

# For jars from Maven Central
- include: source_maven.yml
  when: corda_source == "maven"

# For jars from local directory
- include: source_local.yml
  when: corda_source == "local"

# For jars from Artifactory (snapshots)
- include: source_artifactory.yml
  when: corda_source == "artifactory"

- name: Copy network-truststore
  become: yes
  become_user: "{{ corda_user }}"
  copy:
    src: "{{ corda_local_path }}/network-root-truststore.jks"
    dest: "{{ corda_dir_location }}/certificates/"
    owner: "{{ corda_user }}"
    group: "{{ corda_user }}"
    mode: 0600
  when: not corda_devmode|bool and corda_initial_registration

- name: Register node
  shell: "java -jar corda.jar --initial-registration --network-root-truststore-password {{ corda_password_truststore }}"
  args:
    chdir: "{{ corda_dir_location }}"
  become: true
  become_user: "{{ corda_user }}"
  notify:
    - start corda
  when: not corda_devmode|bool and corda_initial_registration

