---
- name: Get corda jars from Maven Central (post 3.0)
  become: yes
  maven_artifact:
    group_id: net.corda
    artifact_id: "{{ item }}"
    version: "{{ corda_version }}"
    extension: jar
    dest: "{{ corda_dir_location }}/{{ item }}.jar"
    repository_url: "http://repo1.maven.org/maven2"
  loop:
    - corda
  when: corda_version is version_compare('3.1','>=')
  notify:
    - start corda
  # module has a bug and repository_url is necessary for now

- name: Ensure good ownership for files
  become: yes
  file:
    path: "{{ corda_dir_location }}/{{ item }}.jar"
    owner: "{{ corda_user }}"
    group: "{{ corda_user }}"
    mode: 0755
  loop:
    - corda
  notify:
    - start corda

