---
- name: Install systemd startup file
  become: yes
  template:
    src: "{{ item }}.service.j2"
    dest: /etc/systemd/system/{{ item }}.service
    owner: root
    group: root
    mode: 0644
  loop:
    - corda
  notify:
    - reload systemd
    - restart corda
